version: 0.2

batch:
  fast-fail: false 
  build-fanout:
    parallelism: 2
    ignore-failure: false
    
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "Running codebuild-tests-run command without using CODEBUILD_CURRENT_SHARD_FILES"
      - mvn test -Dtest="src/test/java/com/example/AdditionTest.java"
      - mvn test -Dtest="com.example.AdditionTest.java"
      - |
        codebuild-tests-run \
          --test-command 'mvn test -Dtest=$(echo "$CODEBUILD_CURRENT_SHARD_FILES" | -mvtr "\n" " ")' \
          --files-search "codebuild-glob-search '**/test/**/*.java'"
         
  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"
